# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7aaf8e4793745dcea42844cdad828b41e21c46927816a562c3148ac4d9a210183c271987c6cd8ae7d5998dcc2584fffb04eeec43762eda607fab70d0cf47a20e

test:
  secret_key_base: 563cdf1bb602cb4af64cc028225f87e9e767defd9f9843d1924310d54214d5633890135448c4511bb9521975be36e23b034c838ca84639fa6fabc119732dbdf3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
